# Generated by Django 5.2 on 2025-05-12 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_document_docunemt_document_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='index',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='timestore',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
