# Generated by Django 5.2 on 2025-06-03 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_file_index_file_notes_file_timestore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='index',
        ),
        migrations.RemoveField(
            model_name='file',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='file',
            name='timestore',
        ),
        migrations.AddField(
            model_name='page',
            name='show_like_document',
            field=models.BooleanField(default=False),
        ),
    ]
