# Generated by Django 5.2 on 2025-06-03 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_file_index_remove_file_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='show_like_sub_document',
            field=models.BooleanField(default=False),
        ),
    ]
