# Generated by Django 5.2 on 2025-06-03 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_page_show_like_sub_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='show_like_sub_document',
        ),
        migrations.AddField(
            model_name='file',
            name='show_like_sub_document',
            field=models.BooleanField(default=False),
        ),
    ]
