# Generated by Django 5.2.1 on 2025-06-19 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_document_created_by_document_is_important_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255, verbose_name='ФИО студента')),
                ('group', models.CharField(max_length=50, verbose_name='Группа')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='achievements/photos/', verbose_name='Фото студента')),
                ('achievement_type', models.CharField(choices=[('olympiad', 'Олимпиада'), ('certificate', 'Сертификат'), ('award', 'Награда'), ('other', 'Другое')], max_length=20, verbose_name='Тип достижения')),
                ('title', models.CharField(max_length=255, verbose_name='Название достижения')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('date_received', models.DateField(verbose_name='Дата получения')),
                ('is_important', models.BooleanField(default=False, verbose_name='Важное достижение')),
                ('document', models.FileField(blank=True, null=True, upload_to='achievements/documents/', verbose_name='Подтверждающий документ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Достижение студента',
                'verbose_name_plural': 'Достижения студентов',
                'ordering': ['-date_received'],
            },
        ),
    ]
