# Generated by Django 5.2.1 on 2025-06-20 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_studentachievement'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobilityProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название программы')),
                ('program_type', models.CharField(choices=[('exchange', 'Программа обмена'), ('internship', 'Стажировка'), ('practice', 'Практика'), ('other', 'Другое')], max_length=20, verbose_name='Тип программы')),
                ('university', models.CharField(max_length=255, verbose_name='Университет/Организация')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('description', models.TextField(verbose_name='Описание программы')),
                ('requirements', models.TextField(verbose_name='Требования к участникам')),
                ('duration', models.CharField(max_length=100, verbose_name='Продолжительность')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активная программа')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Программа мобильности',
                'verbose_name_plural': 'Программы мобильности',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='MobilityMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('photo', 'Фотография'), ('video', 'Видео')], max_length=10, verbose_name='Тип медиа')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('file', models.FileField(upload_to='mobility/media/', verbose_name='Файл')),
                ('video_url', models.URLField(blank=True, verbose_name='Ссылка на видео (YouTube, Vimeo)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='main.mobilityprogram', verbose_name='Программа')),
            ],
            options={
                'verbose_name': 'Медиа мобильности',
                'verbose_name_plural': 'Медиа мобильности',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
